{{- if (eq (env "DEVELOPMENT_ENVIRONMENT") "true") }}
http:
  services:
    traefik:
      loadBalancer:
        servers:
          - url: http://traefik:8080
  routers:
    traefik:
      rule: Host(`traefik.{{ env "DOMAIN" }}`)
      service: traefik
      tls: {}
{{- end }}
